package vista;

import conexion.Conexion;
import controlador.CtrlRegistrarVenta;
import controlador.VentaPDF;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleVenta;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import modelo.CabeceraVenta;
import java.sql.PreparedStatement;

/**
 *
 * @author Toshiba
 */
public class InterFacturacion extends javax.swing.JInternalFrame {

    // Modelo de los datos
    private DefaultTableModel modeloDatosProductos;

    //Declaramos una lista para el detalle de venta de los productos
    ArrayList<DetalleVenta> listaProductos = new ArrayList();
    //Declaramos objeto de la clase DetalleVenta
    private DetalleVenta producto;

    private int idCliente = 0; //id del cliente seleccionado

    private int idProducto = 0;
    private String nombre = "";
    private int cantidadProductoBBDD = 0;
    private double precioUnitario = 0.00;
    private int porcentajeIva = 0;

    private int cantidad = 0;//cantidad de productos a comprar
    private double subtotal = 0.00;//cantidad por precio
    private double descuento = 0.00;
    private double iva = 0.00;
    private double totalPagar = 0.00;

    // Variables para calculos globales
    private double subtotalGeneral = 0.00;
    private double descuentoGeneral = 0.00;
    private double ivaGeneral = 0.00;
    private double totalPagarGeneral = 0.00;
    // fin de variables globales

    private int auxIdDetalle = 1;//id del deatalle de venta

    public InterFacturacion() {
        initComponents();

        this.setSize(new Dimension(800, 600));
        this.setTitle("Facturación");

        // Cargar los clientes en la vista
        this.CargarComboClientes();
        //Cargar los productos en la vista
        this.CargarComboProducto();

        this.inicializarTablaProducto();

        txtEfectivo.setEnabled(false);
        jButtonCalcularCambio.setEnabled(false);

        txtSubtotal.setText("0.00");
        txtIva.setText("0.00");
        txtDescuento.setText("0.00");
        txtTotalPagar.setText("0.00");

        // Insertar imagen en JLabel
        ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(800, 600, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    // Metodo para inicializar la tabla de los productos
    private void inicializarTablaProducto() {
        modeloDatosProductos = new DefaultTableModel();
        // Añadir las columnas

        modeloDatosProductos.addColumn("N");
        modeloDatosProductos.addColumn("Nombre");
        modeloDatosProductos.addColumn("Cantidad");
        modeloDatosProductos.addColumn("P.Unitario");
        modeloDatosProductos.addColumn("Subtotal");
        modeloDatosProductos.addColumn("Descuento");
        modeloDatosProductos.addColumn("Iva");
        modeloDatosProductos.addColumn("Total Pagar");
        modeloDatosProductos.addColumn("Acción");

        // Agregar los datos del modelo a la tabla
        this.jTableProductos.setModel(modeloDatosProductos);
    }

    // Metodo para presentar la información de la tabla DetalleVenta
    private void listaTablaProductos() {
        this.modeloDatosProductos.setRowCount(listaProductos.size());
        for (int i = 0; i < listaProductos.size(); i++) {
            this.modeloDatosProductos.setValueAt(i + 1, i, 0);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getNombre(), i, 1);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getCantidad(), i, 2);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getPrecioUnitario(), i, 3);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getSubTotal(), i, 4);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getDescuento(), i, 5);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getIva(), i, 6);
            this.modeloDatosProductos.setValueAt(listaProductos.get(i).getTotalPagar(), i, 7);
            this.modeloDatosProductos.setValueAt("Eliminar", i, 8);// aqui luego poner un botón de eliminar
        }
        // Añadir al JTable
        jTableProductos.setModel(modeloDatosProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        txtClienteBuscar = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jButtonAñadirProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        jButtonCalcularCambio = new javax.swing.JButton();
        jButtonRegistrarVenta = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facturación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        jComboBoxCliente.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxCliente.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        jComboBoxProducto.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxProducto.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        txtClienteBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtClienteBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClienteBuscar.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtClienteBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, -1));

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, -1));

        jButtonBuscaCliente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscaCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscaCliente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBuscaCliente.setText("Buscar");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 80, -1));

        jButtonAñadirProducto.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAñadirProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAñadirProducto.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAñadirProducto.setText("Añadir Productos");
        jButtonAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 160, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 760, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Subtotal:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descuento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Iva:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total a Pagar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Efectivo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        txtSubtotal.setEnabled(false);
        jPanel2.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        txtDescuento.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento.setForeground(new java.awt.Color(0, 0, 0));
        txtDescuento.setEnabled(false);
        jPanel2.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        txtIva.setBackground(new java.awt.Color(255, 255, 255));
        txtIva.setForeground(new java.awt.Color(0, 0, 0));
        txtIva.setEnabled(false);
        jPanel2.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        txtTotalPagar.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalPagar.setEnabled(false);
        jPanel2.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        txtEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        txtEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, -1));

        txtCambio.setBackground(new java.awt.Color(255, 255, 255));
        txtCambio.setForeground(new java.awt.Color(0, 0, 0));
        txtCambio.setEnabled(false);
        jPanel2.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, -1));

        jButtonCalcularCambio.setBackground(new java.awt.Color(51, 255, 255));
        jButtonCalcularCambio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCalcularCambio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCalcularCambio.setText("Calcular Cambio");
        jButtonCalcularCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularCambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCalcularCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 380, 210));

        jButtonRegistrarVenta.setBackground(new java.awt.Color(51, 255, 255));
        jButtonRegistrarVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRegistrarVenta.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jButtonRegistrarVenta.setText("Registrar Venta");
        jButtonRegistrarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
        // TODO add your handling code here:
        String ClienteBuscar = txtClienteBuscar.getText().trim();
        Connection cn = Conexion.conectar();
        String sql = "SELECT nombre, apellido FROM cliente WHERE dni = '" + ClienteBuscar + "'";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                jComboBoxCliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido"));

            } else {
                jComboBoxCliente.setSelectedItem("Seleccione cliente:");
                JOptionPane.showMessageDialog(null, "Dni del cliente incorrecta o no encontrada");

            }
            txtClienteBuscar.setText("");
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al buscar cliente" + e);
        }
    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed

    private void jButtonAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirProductoActionPerformed
        // TODO add your handling code here:
        String combo = this.jComboBoxProducto.getSelectedItem().toString();
        // Validar que seleccione un producto
        if (combo.equalsIgnoreCase("Seleccione producto:")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Producto");
        } else {
            // Validar que ingrese una cantidad
            if (!txtCantidad.getText().isEmpty()) {
                // Validar que el usuario no ingrese caractéres no numéricos
                boolean validacion = validar(txtCantidad.getText());
                if (validacion == true) {
                    // Validar que la cantidad sea mayor a cero
                    if (Integer.parseInt(txtCantidad.getText()) > 0) {
                        cantidad = Integer.parseInt(txtCantidad.getText());
                        //ejecutar metodo para obtener datos del producto
                        this.DatosDelProducto();
                        //Validar que la cantidad de producto seleccionado no sea mayor a la base de datos
                        if (cantidad <= cantidadProductoBBDD) {

                            subtotal = precioUnitario * cantidad;
                            totalPagar = subtotal + iva + descuento;

                            // Redondear decimales
                            subtotal = (double) Math.round(subtotal * 100) / 100;
                            iva = (double) Math.round(iva * 100) / 100;
                            descuento = (double) Math.round(descuento * 100) / 100;
                            totalPagar = (double) Math.round(totalPagar * 100) / 100;

                            //Se crea un nuevo producto
                            producto = new DetalleVenta(auxIdDetalle,
                                    1,
                                    idProducto,
                                    nombre,
                                    Integer.parseInt(txtCantidad.getText()),
                                    precioUnitario,
                                    subtotal,
                                    descuento,
                                    iva,
                                    totalPagar,
                                    1);

                            // Añadir a la lista
                            listaProductos.add(producto);
                            JOptionPane.showMessageDialog(null, "Producto Agregado");
                            auxIdDetalle++;
                            txtCantidad.setText("");// Limpiar el campo
                            // Volver a cargar el combo producto

                            this.CargarComboProducto();
                            this.CalcularTotalPagar();
                            txtEfectivo.setEnabled(true);
                            jButtonCalcularCambio.setEnabled(true);

                        } else {
                            JOptionPane.showMessageDialog(null, "La cantidad supera el Stock");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad no puede ser 0 (cero), ni negativa");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "En la cantidad no se admiten caracteres no numéricos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad de productos");
            }
        }
        // Llamar al método
        this.listaTablaProductos();
    }//GEN-LAST:event_jButtonAñadirProductoActionPerformed

    private void jButtonCalcularCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularCambioActionPerformed
        // TODO add your handling code here:
        if (!txtEfectivo.getText().isEmpty()) {
            // Validamos que el usuario no ingrese otro caracteres no numéricos
            boolean validacion = validarDouble(txtEfectivo.getText());
            if (validacion == true) {
                // Validar que el efectivo sea mayor a cero(0)
                double efc = Double.parseDouble(txtEfectivo.getText().trim());
                double tpr = Double.parseDouble(txtTotalPagar.getText().trim());

                if (efc < tpr) {
                    JOptionPane.showMessageDialog(null, "El dinero en efectivo no es suficiente");
                } else {

                    double cambio = efc - tpr; // Cálculo del cambio
                    double cambi = (double) Math.round(cambio * 100d) / 100; // Redondeo a 2 decimales

// Formato para siempre mostrar dos decimales
                    DecimalFormat formato = new DecimalFormat("#.00");
                    String camb = formato.format(cambi); // Formatea el valor redondeado
                    txtCambio.setText(camb); // Muestra en el campo de texto

                }

            } else {
                JOptionPane.showMessageDialog(null, "No se admiten caracteres no numéricos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese dinero en efectivo para calcular cambio");
        }
    }//GEN-LAST:event_jButtonCalcularCambioActionPerformed
    int idArrayList = 0;
    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        // TODO add your handling code here:
        int filaPoint = jTableProductos.rowAtPoint(evt.getPoint());
        int columnaPoint = 0;

        if (filaPoint > -1) {
            idArrayList = (int) modeloDatosProductos.getValueAt(filaPoint, columnaPoint);
        }
        int opcion = JOptionPane.showConfirmDialog(null, "¿Eliminar Producto?");
        // Opciones de confir dialog - (si = 0; no = 1; cancela = 2 ; close = -1)

        switch (opcion) {
            case 0: // presiona si
                listaProductos.remove(idArrayList - 1);
                this.CalcularTotalPagar();
                this.listaTablaProductos();
                break;
            case 1:   // presiona no
                break;
            default: // sea que presione cancela (2) o close (-1)
                break;
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jButtonRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarVentaActionPerformed
        // TODO add your handling code here:
        CabeceraVenta cabeceraVenta = new CabeceraVenta();
        DetalleVenta detalleVenta = new DetalleVenta();
        CtrlRegistrarVenta controlRegistrarVenta = new CtrlRegistrarVenta();

        String fechaActual = "";
        Date date = new Date();
        fechaActual = new SimpleDateFormat("yyyy/MM/dd").format(date);

        if (!jComboBoxCliente.getSelectedItem().equals("Seleccione cliente:")) {
            if (listaProductos.size() > 0) {

                // Metodo para obtener el id del cliente
                this.ObtenerIdCliente();
                // Registrar cabecera
                cabeceraVenta.setIdCabeceraVenta(0);
                cabeceraVenta.setIdCliente(idCliente);
                cabeceraVenta.setValorPagar(Double.parseDouble(txtTotalPagar.getText()));
                cabeceraVenta.setFechaVenta(fechaActual);
                cabeceraVenta.setEstado(1);

                if (controlRegistrarVenta.guardar(cabeceraVenta)) {
                    JOptionPane.showMessageDialog(null, " Venta registrada");
                     
                    // Generar la factura de venta
                    VentaPDF pdf = new VentaPDF();
                    pdf.DatosCliente(idCliente);
                    pdf.generarFacturaPDF();
                    
                    
                    // Guardar detalle
                    for (DetalleVenta elemento : listaProductos) {
                        detalleVenta.setIdDetalleVenta(0);
                        detalleVenta.setIdCabeceraVenta(0);
                        detalleVenta.setIdProducto(elemento.getIdProducto());
                        detalleVenta.setCantidad(elemento.getCantidad());
                        detalleVenta.setPrecioUnitario(elemento.getPrecioUnitario());
                        detalleVenta.setSubTotal(elemento.getSubTotal());
                        detalleVenta.setDescuento(elemento.getDescuento());
                        detalleVenta.setIva(elemento.getIva());
                        detalleVenta.setTotalPagar(elemento.getTotalPagar());
                        detalleVenta.setEstado(1);

                        if (controlRegistrarVenta.guardarDetalle(detalleVenta)) {
                            //  System.out.println("Detalle de venta registrado");

                            txtSubtotal.setText("0.00");
                            txtIva.setText("0.00");
                            txtDescuento.setText("0.00");
                            txtTotalPagar.setText("0.00");
                            txtEfectivo.setText("0.00");
                            txtCambio.setText("0.00");
                            auxIdDetalle = 1;

                            this.CargarComboClientes();
                            this.RestarStockProductos(elemento.getIdProducto(), elemento.getCantidad());

                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar detalle de venta ");
                        }

                    }

                    // Vaciamos la lista
                    listaProductos.clear();
                    listaTablaProductos();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar cabecera de venta ");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }
    }//GEN-LAST:event_jButtonRegistrarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirProducto;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonCalcularCambio;
    private javax.swing.JButton jButtonRegistrarVenta;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableProductos;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClienteBuscar;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtSubtotal;
    public static javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

    /*   
 Metodo para cargar los clientes en el jComboBoxCliente
     */
    private void CargarComboClientes() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM cliente";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBoxCliente.removeAllItems();
            jComboBoxCliente.addItem("Seleccione cliente:");
            while (rs.next()) {
                jComboBoxCliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar clientes" + e);
        }
    }


    /*   
 Metodo para cargar los productos en el jComboBoxCliente
     */
    private void CargarComboProducto() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM producto";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBoxProducto.removeAllItems();
            jComboBoxProducto.addItem("Seleccione producto:");
            while (rs.next()) {
                jComboBoxProducto.addItem(rs.getString("nombre"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar productos" + e);
        }
    }

    /*   
 Metodo para validar que el usuario no ingrese caracteres no numéricos
     */
    private boolean validar(String valor) {
        try {
            int num = Integer.parseInt(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /*   
 Metodo para validar que el usuario no ingrese caracteres no numéricos
     */
    private boolean validarDouble(String valor) {
        try {
            double num = Double.parseDouble(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    /*   
 Metodo para mostrar los datos del producto seleccionado
     */
    private void DatosDelProducto() {
        try {
            String sql = "SELECT * FROM producto WHERE nombre = '" + this.jComboBoxProducto.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idProducto = rs.getInt("IdProducto");
                nombre = rs.getString("nombre");
                cantidadProductoBBDD = rs.getInt("cantidad");
                precioUnitario = rs.getDouble("precio");
                porcentajeIva = rs.getInt("porcentajeIva");
                this.CalcularIva(precioUnitario, porcentajeIva);// calcula y retorna el iva
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener datos del producto" + e);
        }
    }

    /*   
 Metodo para calcular iva
     */
    private double CalcularIva(double precio, int porcentajeIva) {
        int p_iva = porcentajeIva;

        switch (p_iva) {
            case 0:
                iva = 0.00;
                break;
            case 10:
                iva = (precio * cantidad) * 0.10;
                break;
            case 21:
                iva = (precio * cantidad) * 0.21;
                break;
            default:
                break;

        }
        return iva;
    }

    // Método para calcular el total a pagar de todos los productos agregados
    private void CalcularTotalPagar() {
        subtotalGeneral = 0;
        descuentoGeneral = 0;
        ivaGeneral = 0;
        totalPagarGeneral = 0;

        for (DetalleVenta elemento : listaProductos) {
            subtotalGeneral += elemento.getSubTotal();
            descuentoGeneral += elemento.getDescuento();
            ivaGeneral += elemento.getIva();
            totalPagarGeneral += elemento.getTotalPagar();
        }
        //Redondear decimales
        subtotalGeneral = (double) Math.round(subtotalGeneral * 100) / 100;
        descuentoGeneral = (double) Math.round(descuentoGeneral * 100) / 100;
        ivaGeneral = (double) Math.round(ivaGeneral * 100) / 100;
        totalPagarGeneral = (double) Math.round(totalPagarGeneral * 100) / 100;

        // Enviar datos a la vista
        txtSubtotal.setText(String.valueOf(subtotalGeneral));
        txtIva.setText(String.valueOf(ivaGeneral));
        txtDescuento.setText(String.valueOf(descuentoGeneral));
        txtTotalPagar.setText(String.valueOf(totalPagarGeneral));
    }

    // Metodo para obtner el id del cliente
    private void ObtenerIdCliente() {
        try {
            String sql = "SELECT * FROM cliente WHERE concat (nombre,' ',apellido) = '" + this.jComboBoxCliente.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCliente = rs.getInt("idCliente");
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener id del cliente." + e);
        }
    }

    // Metodo para restar la cantidad (stock) de los productos vendidos
    private void RestarStockProductos(int idProducto, int cantidad) {
        int cantidadProductosBaseDeDatos = 0;
        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT idProducto, cantidad FROM producto WHERE idProducto = '" + idProducto + "'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cantidadProductosBaseDeDatos = rs.getInt("cantidad");
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al restar cantidad 1." + e);
        }
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement("UPDATE producto SET cantidad = ? WHERE idProducto ='" + idProducto + "'");
            int cantidadNueva = cantidadProductosBaseDeDatos - cantidad;
            consulta.setInt(1, cantidadNueva);
            if(consulta.executeUpdate() > 0) {
                System.out.println("Todo bien");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al restar cantidad 2." + e);
        }
    }
}
