package vista;

import conexion.Conexion;
import controlador.CtrlProducto;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Producto;

/**
 *
 * @author Toshiba
 */
public class InterActualizarStock extends javax.swing.JInternalFrame {

    // Variables globales
    int idProducto = 0;
    int cantidad = 0;

    public InterActualizarStock() {
        initComponents();
        setTitle("Actualizar Stock de los Productos");
        setSize(new Dimension(400, 300));
        this.cargarComboProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadActual = new javax.swing.JTextField();
        txtCantidadNueva = new javax.swing.JTextField();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar Stock de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Stock Actual:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Stock Nuevo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtCantidadActual.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidadActual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantidadActual.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidadActual.setEnabled(false);
        getContentPane().add(txtCantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        txtCantidadNueva.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidadNueva.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantidadNueva.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidadNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, -1));

        jComboBoxProducto.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxProducto.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, 30));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
        // TODO add your handling code here:
        this.MostrarStock();
    }//GEN-LAST:event_jComboBoxProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // Validamos seleccion de producto
        if (!jComboBoxProducto.getSelectedItem().equals("Seleccione productos:")) {
            // Validamos campos vacios
            if (!txtCantidadNueva.getText().isEmpty()) {
                // Validamos que el usuario no ingrese otros caracteres no numericos
                boolean validacion = validar(txtCantidadNueva.getText().trim());
                if (validacion == true) {
                    //validamos que la cantidad sea mayor a (0)
                    if (Integer.parseInt(txtCantidadNueva.getText()) > 0) {

                        Producto producto = new Producto();
                        CtrlProducto controlProducto = new CtrlProducto();
                        int stockActual = Integer.parseInt(txtCantidadActual.getText().trim());
                        int stockNuevo = Integer.parseInt(txtCantidadNueva.getText().trim());

                        stockNuevo = stockActual + stockNuevo;
                        producto.setCantidad(stockNuevo);

                        if (controlProducto.actualizarStock(producto, idProducto)) {
                            JOptionPane.showMessageDialog(null, "Stock Actualizado");
                            jComboBoxProducto.setSelectedItem("Seleccione producto:");
                            txtCantidadActual.setText("");
                            txtCantidadNueva.setText("");
                            this.cargarComboProductos();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al actualizar");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad no puede ser ni cero ni negativa");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "En la cantidad no se admiten caracteres no numericos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese una nueva cantidad para sumar el stock del producto");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txtCantidadActual;
    private javax.swing.JTextField txtCantidadNueva;
    // End of variables declaration//GEN-END:variables

    //Metodo para cargar los productos en JComboBox
    private void cargarComboProductos() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM producto";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBoxProducto.removeAllItems();
            jComboBoxProducto.addItem("Seleccione productos:");

            while (rs.next()) {
                jComboBoxProducto.addItem(rs.getString("nombre"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar los productos en: " + e);
        }
    }

    // Metodo para mostrar stock del producto seleccionado
    private void MostrarStock() {
        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM producto WHERE nombre = '" + this.jComboBoxProducto.getSelectedItem() + "'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                idProducto = rs.getInt("idProducto");
                cantidad = rs.getInt("cantidad");
                txtCantidadActual.setText(String.valueOf(cantidad));
            } else {
                txtCantidadActual.setText("");
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener stock del producto: " + e);
        }
    }
    // Metodo de validacion de caracteres no numericos

    private boolean validar(String valor) {
        int num;
        try {
            num = Integer.parseInt(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
